02 components
Genesis-Solutions/Gomez-Morin-Frontend pull request #4
Opened 2023-04-21 00:31 UTC by FlavioRr

## Descripción
<-- Agregar una descripción concisa de lo que hace el pull request !-->

6 componentes han sido terminados:
CardImage
GalleryCard
TextContainer
TextButton
IconTitle
DropdownText

## Resumen de cambios
<-- Enlistar los commits hechos del pull request !-->

4 commits=
Commit inicial = Card Image, GalleryCard y TextButton
2do commit = Text Container
3ro commit = IconTitle
4to commit= DropdownText

## Notas (opcional)
<-- Agregar notas para explicar aspectos adicionales del pull request !-->

N/A

2023-04-24 16:22 UTC, MandukoGR requested changes

2023-04-24 16:22 UTC, MandukoGR commented on GomezMorinFrontEnd/src/App.jsx
> +
Usar Prettier

2023-04-24 16:22 UTC, MandukoGR commented on GomezMorinFrontEnd/src/components/CardImage.jsx
> +  return (
Usar Prettier

2023-04-24 16:22 UTC, MandukoGR commented on GomezMorinFrontEnd/src/components/GalleryCard.jsx
> +const GalleryCard = ({icon1, icon2, icon3}) => {
Usar prettier

2023-04-24 16:22 UTC, MandukoGR commented on GomezMorinFrontEnd/src/components/GalleryCard.jsx
> +const GalleryCard = ({icon1, icon2, icon3}) => {
Mejor usen un arreglo de icons y un map

2023-04-25 05:51 UTC, AriannFernando approved these changes
Apruebo estos cambios

2023-04-25 05:53 UTC, merged