00 components
Genesis-Solutions/Gomez-Morin-Frontend pull request #5
Opened 2023-04-21 04:46 UTC by AriannFernando

## Descripción
Este pull request contiene los componentes de Button, InputForm, Layout, ModalAlert, Navbar, NavbarDropdownItem, NavbarItem

## Resumen de cambios
1. Se implementó el componente Navbar, el NavbarItem, Layout
2. Se implementó la primera iteración del modal Alert
3. Se corrigió la forma de mostrar el modal Alert
4. Se implementó el componente de Boton
5. Se implementó el componente de Imput Form y correción a errores del boton
6. Se corrigieron errores estéticos de los componentes
7. Se agregaron los comentarios de los componentes de JavaDoc

## Notas (opcional)
<-- Agregar notas para explicar aspectos adicionales del pull request !-->

2023-04-24 16:42 UTC, MandukoGR requested changes
Agregar returns en comentarios
Eliminar páginas de pages

2023-04-24 16:42 UTC, MandukoGR commented on GomezMorinFrontEnd/src/components/ButtonNavigation.jsx
> + */
Se repite código de Button.jsx

2023-04-24 16:42 UTC, MandukoGR commented on GomezMorinFrontEnd/src/components/Card.jsx
> +    console.log(id);
Quitar console log

2023-04-24 16:42 UTC, MandukoGR commented on GomezMorinFrontEnd/src/App.jsx
>  function App() {
Cambiar por arrow function

2023-04-25 04:56 UTC, Mike5801 approved these changes
Approved 00 components

2023-04-25 04:59 UTC, Mike5801 approved these changes
Approve changes

2023-04-25 05:00 UTC, Mike5801 approved these changes

2023-04-25 05:06 UTC, merged