03 components
Genesis-Solutions/Gomez-Morin-Frontend pull request #6
Opened 2023-04-22 22:28 UTC by Mike5801

## Descripción
<-- Agregar una descripción concisa de lo que hace el pull request !-->
Agrega los componentes Carousel, Datagrid, EditModal, SearchBar y DropdownInput

## Resumen de cambios
<-- Enlistar los commits hechos del pull request !-->
1.- Add Carousel component
2.- Add Datagrid component
3.- add Clipboard component
4.- add ImageTitle component
5.- fix Carousel component
6.- add code formatter
7.- add DropdownInput and EditModal components
8.- add search bar component

## Notas (opcional)
<-- Agregar notas para explicar aspectos adicionales del pull request !-->
Se importaron los botones de otra rama para hacer el edit modal. Atender al merge conflict de ser necesario

2023-04-24 15:53 UTC, MandukoGR requested changes

2023-04-24 15:53 UTC, MandukoGR commented on GomezMorinFrontEnd/src/components/EditModal.jsx
> +    console.log(data);
Quitar console log

2023-04-24 15:53 UTC, MandukoGR commented on GomezMorinFrontEnd/src/components/DropdownInput.jsx
> + */
Falta agregar return

2023-04-25 05:55 UTC, AriannFernando approved these changes
Apruebo estos cambios

2023-04-25 06:05 UTC, merged