add hot fix startday
Genesis-Solutions/Gomez-Morin-Frontend pull request #60
Opened 2023-05-26 06:01 UTC by FlavioRr

## Descripción
<-- Agregar una descripción concisa de lo que hace el pull request !-->
Agregamos la restriccion de que no se pueda agregar una fecha final antes de la inicial

## Resumen de cambios
<-- Enlistar los commits hechos del pull request !-->

commit 1:  Agregamos la restriccion de que no se pueda agregar una fecha final antes de la inicial

## Notas (opcional)
<-- Agregar notas para explicar aspectos adicionales del pull request !-->

2023-05-26 15:16 UTC, MandukoGR requested changes
Usen el componente de InputForm y usen prettier en sus páginas.

2023-05-26 15:16 UTC, MandukoGR commented on GomezMorinFrontEnd/src/pages/RequestForm/InitialForm.jsx
> +              className="border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 w-full p-2.5"
Usen el componente de InputForm

2023-05-26 15:16 UTC, MandukoGR commented on GomezMorinFrontEnd/src/pages/RequestForm/InitialForm.jsx
> +              className="border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 w-full p-2.5"
Utilizen InputForm

2023-05-26 15:16 UTC, MandukoGR commented on GomezMorinFrontEnd/src/pages/RequestForm/SpecificForm.jsx
> +			max={currentDate}
Usen prettier

2023-05-27 05:37 UTC, aruizgarciarojas approved these changes
Muy bien mi TL <3

2023-05-31 17:35 UTC, MandukoGR approved these changes

2023-05-31 17:35 UTC, merged